### ISSUE TITLE
Implement single intermediate node with forward and backward connections

### ISSUE THREAD

**Issue by DestructiveReasoning** [CamiloGarciaLaRotta/Cebolla#12]
To start progress on getting this onion working, let's implement one single intermediate onion node that has connections to both the originator and a dummy destination in `onion_router.py`.

Criteria:
- [x] Design method for listening on both forward and backward connections
- [x] Make forward connection and thread to pass message forward
- [x] Make backward connection (and possibly thread ) for passing messages backward
- [x] Test sending message to destination through the intermediate node and receive the response.
- [x] Test sending message through multiple intermediate nodes and receive response

**Comment by stumash** [comment]
development started on branch [interNode-12](/CamiloGarciaLaRotta/Cebolla/tree/interNode-12)
