### ISSUE TITLE
Implement Onion Routing CLI Client

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [CamiloGarciaLaRotta/Cebolla#14]
Developing a CLI client will advance the project in two main fields:

- **Testing:** Facilitate development and execution of complex test cases
- **Development**: An intrinsic part of the product is to have a client interface. It is part of the components to be delivered at the end of the project

Criteria:
- [x] Adhere to the current communication handshake and transmission interface used by `onion_router.py`
- [x] Obtention of virtual circuit path from `directory.py`
- [x] Provide multiple verbose logging levels: error only, error and status
- [x] User input and Network error handling

**Comment by DestructiveReasoning** [comment]
Looks good. This will be very helpful for development and testing.

**Comment by CamiloGarciaLaRotta** [comment]
@DestructiveReasoning  @stumash 
Here is the proposed interface for the first iteration of `onion_client.py`:

Continuous prompt in which client send plain text messages to multiple destinations and in which it will receive the plain text response from them (_i.e._ One process per host handling all communication steps for all destinations).

**Scenario**
- User executes `onion_client.py`
- Display continous prompt and expect an available command

**Available Commands:**
- `connect <hostname>` 
   - Get path from `directory.py`
   - Send encrypted setup onions to path nodes
   - Inform client result of connection setup
   - Continoulsy prompt user for plain text message to be sent to `<hostname>`
   -  Encapsulate and encrypt messages
   -  Decrypt and display plain text response
- `status`
   - Display information on the current connection such as nodes in the path, symkeys, src/dst ports
- `exit` or `Ctrl-C` 
   - If inside a connection with a hostname, it will close that connection, return to main prompt in which client can connect to other `<hostname>`
  - if in the main prompt, it will close the listening ports and exit `onion_client.py`

**NB:** 
- This first iteration does not support multiple open connections at the same time. One thread per communication is needed to achieve this specification. This will be the focus of the second iteration of the `onion_client.py` once the base frame is coded.  
- At this stage, the client is not yet capable of receiving a packet from a random source and setting up a connection with it. A multithreaded client is required for that matter. This will be the focus of the third iteration of the `onion_client.py` once a multithreaded version of it is coded.

**Comment by DestructiveReasoning** [comment]
What do you mean by this:

> At this stage, the client is not yet capable of receiving a packet from a random source and setting up  a connection with it. A multithreaded client is required for that matter. This will be the focus of the third iteration of the onion_client.py once a multithreaded version of it is coded.

You're saying the originator client cannot act as an intermediate onion node? I don't think that's even necessary - if the originator wanted to be an onion node he can run `onion_router.py` on port 5551 separately from the onion client, which should work. On that note, concerning this: 

>This first iteration does not support multiple open connections at the same time. One thread per communication is needed to achieve this specification. This will be the focus of the second iteration of the onion_client.py once the base frame is coded.

I don't think that's an issue either. As I understand it, if the user running the onion client opens two instances of the onion client, it will be sending messages from different (random) ports, so I think that will work as well. Again, as I understand it, the onion client doesn't ever need to listen on a globally-known port, so I don't think we really need to worry about multithreading for the sake of the client, at least not for now.

Lastly, concerning "Send encrypted setup onions to path nodes" and "Encapsulate and encrypt messages", don't worry about encryption for now, it's not 100% ready yet. The remainder of it depends on the functionality provided by the client. Once the client is done, I will be able to finish the rest of the crypto stuff fairly easily. My crypto setup so far is pretty modular so once the client is ready, I will be able to basically instantiate some classes and call a few methods to implement the cryptography without changing the structure of the client.

**Comment by CamiloGarciaLaRotta** [comment]
Perfect, 
because a pic is worth a thousand words => src code is worth a thousand docs
then I'll push my frame code so that we can discuss your points directly on it

**Comment by stumash** [comment]
Src <<< docs IMO

**Comment by CamiloGarciaLaRotta** [comment]
valid, but given our time constraints, to present an idea it is more efficient to show a prototype
