### ISSUE TITLE
Current onion router implementation always sends messages to the same port

### ISSUE THREAD

**Issue by DestructiveReasoning** [CamiloGarciaLaRotta/Cebolla#15]
Right now, the onion nodes all connect to the next target at the same port, notably:
```
forw_conn.connect((msg_addr, PORT))
```
This is perfectly reasonable for the sake of passing messages across the onion network, however this will ultimately fail if the originator wishes to send a message to some arbitrary server. Most likely the arbitrary server won't be listening on the port specified by `PORT`, so the originator's message will not be received. Perhaps we should include a `"port"` parameter to JSON messages (or at least just to the innermost layer)? 

This is a design decision that we'll need to agree on.

**Comment by stumash** [comment]
Very true. Yes I believe the right thing to do is have the port to send to be in the json. Note that we will still have nodes be listening on a specific port the whole time, but now which port the next node in the path listens on will be on the json instead of as a clarg

**Comment by DestructiveReasoning** [comment]
@stumash Yup. I'll try to get this done tonight then.

**Comment by DestructiveReasoning** [comment]
Actually, I think we may need to keep the command line argument. Unless you want the directory to send port numbers to the originator when it sends the public keys. Either way sounds fair to me, but the directory approach may be more robust. @CamiloGarciaLaRotta let me know what you think as well

**Comment by CamiloGarciaLaRotta** [comment]
I am completely onboard to implement the port parameter, either way, I do find it' s a very useful feature.
probably not for this deliverable but if we keep working on this project it would enable us to showcase accessing the WWW through our Cebolla routing network

**Comment by DestructiveReasoning** [comment]
Starting progress on branch [customPorts-15](https://github.com/Cebolla/tree/customPorts-15).
Here's what I'll do for now:
- [x] Modify `onion_router/onion_router.py` to check if there's a `"port"` parameter in the JSON that it receives and pass it to that port. Otherwise pass it to port 80 (or maybe a more sane default).
- [x] Modify `stealth/onion.py` to include the `"port"` parameter to the onions it creates

I figured port 80 is the safe bet to go for the default port. Realistically, all onion nodes don't have to be running on the same port. Don't forget, we'll be automating the onion creation process anyway, so if it's easier we can always enforce running the onion nodes on a common port and just have the onioning function set the port of all intermediate nodes to a fixed value. 

@CamiloGarciaLaRotta, maybe for your implementation of the client you can have the user specify a port number for the destination as well?

**Comment by DestructiveReasoning** [comment]
Guys. I had a bit of a revelation. Check out [this bug](https://github.com/CamiloGarciaLaRotta/Cebolla/issues/16). Please take a look ASAP so we can take action.
