### ISSUE TITLE
Deploy scripts are deprecated

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [CamiloGarciaLaRotta/Cebolla#27]
The deploy scripts have proven very useful in automating tests.
Unfortunately, they are deprecated with respect to the current use of `client`, `directory`, `router`, `destination`.

Once the encryption feature is implemented we must:
- [ ] Update each deploy script to adhere to the final implementation of each onion component
- [ ] Develop a master `deploy.sh` that will call all sub-deploy scripts

**Comment by CamiloGarciaLaRotta** [comment]
This is a good practice for Testing team to familiarize themselves with the way of calling each onion component and giving insight into how to automate the tests afterwards

**Comment by stumash** [comment]
Specifically, the deploy scripts are missing the `dir_port` arg

**Comment by CamiloGarciaLaRotta** [comment]
yep

**Comment by Dakos-Industries** [comment]
I have created new scripts that handle the deployement and I will be pushing them soon and they will be available on the testing branch for review .
