### ISSUE TITLE
Make encrypted data in onion packets uniform in length

### ISSUE THREAD

**Issue by DestructiveReasoning** [CamiloGarciaLaRotta/Cebolla#4]
The ciphertext yielded by AES varies in length based on the size of the plaintext message. Therefore, the encrypted data becomes shorter in length as it migrates from the originator to the destination. Perhaps we should add some padding to keep the ciphertext length uniform the whole way through. Otherwise it may be possible to trace the message path by considering the varying lengths of the packets being sent from node to node.

**Comment by stumash** [comment]
I very much agree and read about this.  The message must be fixed in size as the layers of onion are peeled.  In fact, I think that all messages should be padded from the get-go, rounded up in length to the nearest *x* bytes, to further prevent length analysis attacks

**Comment by DestructiveReasoning** [comment]
@stumash Yeah, agreed as well. So we need to agree upon such a value *x* to cap and fix our message sizes at. Shouldn't actually be a difficult fix, I don't think.

**Comment by DestructiveReasoning** [comment]
Starting progress in branch [uniformCiphers-4](/CamiloGarciaLaRotta/Cebolla/tree/uniformCiphers-4)

**Comment by DestructiveReasoning** [comment]
I believe it is impossible to have uniformly-sized messages in the scheme we have now. If intermediate nodes don't know their neighbours' symmetric keys, they cannot pad the message after they decrypted their layer. Stopping progress on this now until we decide how (or if) we will take care of this. In the meantime, I'm working on an alternative solution, see #7.

**Comment by DestructiveReasoning** [comment]
Development being done in the `uniformCipherLength-4` branch. 
The problem will be resolved by making each node aware of the previous node's symmetric key. Using this knowledge, intermediate nodes may pad the next node's ciphertext, and the next node can then decrypt with the previous symmetric key, remove padding, decrypt with his symmetric key, add padding, and then encrypt with his symmetric key before sending to the next node. 

Below is a list of features that must be implemented:
- [x]  Make nodes aware of previous symkey
- [x]  Implement padding/unpadding logic
- [x]  Design padding scheme to avoid using repeated characters
- [x]  Implement second random number generator for each node to randomize initialization vectors for padding decryption
