### ISSUE TITLE
Make message type sane in onion layering functions

### ISSUE THREAD

**Issue by DestructiveReasoning** [CamiloGarciaLaRotta/Cebolla#5]
Right now data is passed in the onion network as JSON objects (or python dictionaries) that contain a "type" field. This will be especially useful in the circuit-establishment routine to differentiate symmetric keys from encrypted data. However, for the purposes of testing in the short term, the *destination* message always has the `MessageType.Data` type value in the forward onion. In the long term, it should have the `MessageType.Onion` type value to make it less distinguishable from other messages.

**Comment by stumash** [comment]
I'm not sure I understand this

**Comment by CamiloGarciaLaRotta** [comment]
@DestructiveReasoning is this still relevant now that we only make an onion for setup?

**Comment by stumash** [comment]
no it is no longer relevant.  Also I'm happy to see you doing cleanup on old issues.  I move to close this issue given that it's not longer relevant.  Do we all agree?
* [x] @DestructiveReasoning 
* [x] @CamiloGarciaLaRotta

**Comment by DestructiveReasoning** [comment]
Agreed

**Comment by stumash** [comment]
I'm closing this issue as permanently and intentionally unresolved.
